# Generated by Django 3.1.2 on 2020-10-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Offer',
            new_name='offer',
        ),
    ]
